#!/bin/bash --login -e

site='bsa166.org'
logfile="${HOME}/Library/Logs/${site}.log"
[ -f ${logfile} ] && mv ${logfile} ${logfile/.log/.prev.log}}

date > ${logfile}

# Note - requires .netrc for authentication
wget --mirror --passive-ftp --wait=1 --directory-prefix=${HOME}/Sites --append-output=${logfile} ftp://${site}

# prune removed files/dirs

for d in `find ${HOME}/Sites/${site} -type d`; do
    
    # might have been pruned already
    if [ -d $d ]; then
        echo cleaning $d
        cd $d
    
        cat .listing | tr -d '\r' | sed -E -n -e 's/^([^ ]+ +){8}//p' | egrep -v '^((\.)|(\.\.)|(\.listing))$' | sort > .listing1
        touch .listing2
        ls -a | egrep -v '^((\.)|(\.\.)|(\.listing))$' | sort > .listing2
        diff .listing1 .listing2 | sed -n -e 's/^> //p'  | xargs rm -r
    fi
done
