#!/bin/bash
# Show (or delete) branches that have been merged to master (or origin/master for remotes)
#
#  git merged-branches
#  git merged-branches --remote
#  git merged-branches --remote --feature
#  git merged-branches --remote --issue
#  git merged-branches --all
#  git merged-branches --delete
#  git merged-branches --delete --remote --feature
#  git merged-branches --delete --remote --issue

allowedOpts=( --remote --all --feature --issue --delete )
. $(dirname $0)/getopts.sh

if [ -n "${args}" ]; then
  echo "Usage: git merged-branches [--remote|--all] [--feature|--issue] [--delete]"
  exit 1
fi

# do not allow --delete with --all or --remote (unless --feature or --issue)
if [ -n "${deleteOpt}" ]; then
  if [ -n "${allOpt}" ]; then
    echo "Can not --delete --all"
    exit 1
  fi
  if [ -n "${remoteOpt}" ]; then
    if [ -z "${featureOpt}${issueOpt}" ]; then
      echo "Can not --delete --remote without --feature or --issue"
      exit 1
    fi
  fi
fi

function dim {
  echo -e -n "\033[90m"  # grey. dim would be \033[2m but not good for my iTerm color scheme
}

function undim {
  echo -e -n "\033[0m"  # reset color
}

trap undim EXIT # reset color

# If doing --remote or --all, first fetch and prune origin
if [ -n "${remoteOpt}${allOpt}" ]; then
  dim
  git fetch --prune
  undim
fi

function mergedBranches {
  # git branch: with --remote, remotes are prefixed with origin/, with --all they are prefixed with remotes/origin/
  git branch $1 ${remoteOpt} ${allOpt} --merged origin/master | egrep -v '^\*{0,1} *((remotes/){0,1}origin/){0,1}master|HEAD(( -> .*)|$)' 
}

function filterBranches {
  if [ -n "${featureOpt}" ]; then
    egrep '^ *(origin/){0,1}feature/'
  elif [ -n "${issueOpt}" ]; then
    egrep '^ *(origin/){0,1}issue/'
  else
    cat
  fi
}

function deleteBranches {
  if [ -n "${deleteOpt}" ]; then
    if [ -n "${remoteOpt}" ]; then
      sed -e 's/^ *\(\(remotes\/\)\{0,1\}origin\/\)\{0,1\}//' | xargs git push --delete origin
    else
      xargs git branch --delete
    fi
  else
    cat
  fi
}

mergedBranches | filterBranches | deleteBranches
