#!/bin/bash
# Formatted log output:
#  Adds text-based branch graph
#  Adds decrate to note ref names (branches and tags) for commits
#  Short one-line display of commit info

# Most options to git-log are allowed (some might conflict with the formatting, but the non-formatting ones are ok)

# Helpful options:
# --branches include all local branches, even if they are not merged into the current HEAD
# --all include all refs
# --first-parent only show the stuff directly committed or merged into this branch (not commits going into a merge)

git log --graph --pretty=format:'%C(yellow)%h%x09%d%Creset %s %Cgreen(%cr) %C(red)<%an>%Creset' --abbrev-commit --date-order "${@}"
