#!/bin/bash
#
# Delete the branch and its remote counterpart

for branch in "${@}"; do

  git branch --delete ${branch} && \
  git push --delete origin ${branch} && \
  git branch --delete --remote origin/${branch}

done

git remote prune origin
