#!/bin/sh
 # git child status --short --branch

if [ "${1}" = "--" ]; then
  # run child-status here in the CWD
  # Simple child dir scan, execute git status --short --branch in each subdir,
  # filter out repos with no changes sitting at master
  master=master
  [ -f .git-child-master ] && master=$(cat .git-child-master)
  if [ "$(git status --short --branch)" != "## ${master}...origin/${master}" ]; then
    git status --short --branch
  fi
else
  git-child child-status --
fi
