#!/bin/sh

rev=${1:-HEAD}
path=${2:- }

git ls-tree -r ${rev} ${path} | while read mode type blob file; do
  promFile=$(echo ${file} | sed -e 's/\([\?\:\.%\\]\)/\\\1/g')
  git cat-file -p ${blob} | less -c -P"?n${promFile} .?e(END) :?pB%pB\%:byte %bB?s/%s...%t" -
done