#!/bin/sh

function killit() {
  pid=$(ps x | grep "$1" | sed -e 's/^ *\([0-9]*\) .*$/\1/')
  if [ -n "${pid}" ]; then
    ps ${pid}
    kill ${2} ${pid}
  else
    echo no ${1//\\}
  fi
}

killit com\\.pointbase
killit derby\\.drda
killit weblogic\\.Server -9
killit catalina\\.startup
killit kv\\lite
