#!/bin/sh

# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0">
# <dict>
#     <key>Label</key>
#     <string>org.mongo.mongod</string>
#     <key>KeepAlive</key>
#     <true/>
#     <key>RunAtLoad</key>
#     <true/>
#     <key>EnableGlobbing</key>
#     <true/>
#     <key>ProgramArguments</key>
#     <array>
#         <string>~/bin/startMongo</string>
#     </array>
# </dict>
# </plist>


DBPATH=~/dev/mongodb

# clean out old stuff
rm -fr ${DBPATH}
mkdir ${DBPATH}

~/lib/mongodb-osx-x86_64-2.4.5/bin/mongod --dbpath ${DBPATH} --smallfiles --logpath ${DBPATH}/mongodb.log
