# .bash_profile

export BASH_SILENCE_DEPRECATION_WARNING=1

# Get environment from bashrc
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

if [ -s "$HOME/.rvm/scripts/rvm" ]; then
  . "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
fi
